const{DB_URI,DB_NAME,DB_USER,AUTH_GOOGLE_ID,AUTH_GOOGLE_SECRET,AUTH_SECRET,HD_API,HD_KEY,YT_API,YT_KEY,X_API,X_CLIENT_ID,X_CLIENT_SECRET,X_BEARER_TOKEN,NEXT_PUBLIC_SELF_URL,NEXT_PUBLIC_GOOGLE_CLIENT_ID,}=process.env
if(!DB_URI||!DB_NAME||!DB_USER||!AUTH_GOOGLE_ID||!AUTH_GOOGLE_SECRET||!AUTH_SECRET||!HD_API||!HD_KEY||!YT_API||!YT_KEY||!X_API||!X_CLIENT_ID||!X_CLIENT_SECRET||!X_BEARER_TOKEN||!NEXT_PUBLIC_SELF_URL||!NEXT_PUBLIC_GOOGLE_CLIENT_ID){
  throw new Error('[THISOE🩵DEBUG] Missing environment variables.')
}

export const
env = {
  DB_URI,DB_NAME,DB_USER,AUTH_GOOGLE_ID,AUTH_GOOGLE_SECRET,AUTH_SECRET,HD_API,HD_KEY,YT_API,YT_KEY,X_API,X_CLIENT_ID,X_CLIENT_SECRET,X_BEARER_TOKEN,NEXT_PUBLIC_SELF_URL,NEXT_PUBLIC_GOOGLE_CLIENT_ID,
},
publicEnv = {
  NEXT_PUBLIC_SELF_URL,
  NEXT_PUBLIC_GOOGLE_CLIENT_ID,
}
