import{AP}from"@/components/_use_client"
import"./thisoe.css"
import type{Metadata}from"next"

export const metadata:Metadata = {
  title: "Thisoe Rankings",
  description: "Generated by create next app",
}

export default function _({children,}:Readonly<{children:React.ReactNode}>){
  return<html lang="en">
    <body>
      <AP>{children}</AP>
    </body>
  </html>
}
